# Source https://medium.com/@remi_collin/testing-laravel-packages-for-backward-compatibility-using-travis-cabc3210e120
language: php

php:
  - 5.6.4
  - 7.2
  - 7.3

env:  
  - LARAVEL_VERSION=5.4.*  
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.0.*

matrix:
  fast_finish: true
  exclude:    
    - php: 5.6.4      
      env: LARAVEL_VERSION=5.8.*
    - php: 5.6.4
      env: LARAVEL_VERSION=6.0.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction 
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;  
  - composer update

script:
  - phpunit
